Events and query structure definitions
martinthomson/raw-ipa pull request #27
Opened 2022-04-26 11:54 UTC by taikiy

Quick implementation of source/trigger events and IPA query data models. Actual parameter types require further reviews but submitting the first try for PoC.

2022-05-10 05:49 UTC, benjaminsavage requested changes
Thanks for submitting this! A few suggestions.

2022-05-10 05:49 UTC, benjaminsavage commented on src/helpers/models.rs
> +type CipherText = [u8; 32];
Isn't there a better type available for representing huge integers? I think there was one with pretty good built-in support.

2022-05-10 05:49 UTC, benjaminsavage commented on src/helpers/models.rs
> +    /// it's the business who promotes ads. For trigger-fanout, it's the business
I think we do not need this at all for trigger-fanout queries, as it will have the same value for all events (source or trigger)

2022-05-10 05:49 UTC, benjaminsavage commented on src/helpers/models.rs
> +    matchkey: SecretShare,
If we want to support multiple matchkeys, this should be a vector of SecretShare.

2022-05-10 05:49 UTC, benjaminsavage commented on src/helpers/models.rs
> +    /// Campaign ID of the ad served to the user.
Per this thread: https://github.com/patcg/private-measurement/issues/9#issuecomment-1121329028 we might want to consider renaming this to "group_id" or even just "breakdown_key".

2022-05-10 05:49 UTC, benjaminsavage commented on src/helpers/models.rs
> +    /// Zero knowledge proom that the trigger value lies within a specific range
spelling: proom => proof

2022-05-10 05:49 UTC, benjaminsavage commented on src/helpers/models.rs
> +    /// Zero knowledge proom that the trigger value lies within a specific range
I'm not sure if this is the best type - but we can always change this later.

2022-05-10 05:49 UTC, benjaminsavage commented on src/helpers/models.rs
> +    Source,
Should we call them "SourceFanout" and "TriggerFanout"?

2022-05-10 05:49 UTC, benjaminsavage commented on src/helpers/models.rs
> +    privacy_budget: f32,
We probably cannot support arbitrarily fine-grained queries. I suspect an integer value would be better than a float. For example, an integer ranging from 1 to 100 might actually be better (i.e. we might want to have a cap on the total number of queries can can make).

2022-05-10 05:49 UTC, benjaminsavage commented on src/helpers/models.rs
> +    cap: u32,
u8 should be fine I think.

2022-05-10 05:49 UTC, benjaminsavage commented on src/helpers/models.rs
> +struct Query {
To disambiguate this against QueryType, I'd suggest renaming this IPAQuery

2022-05-10 08:42 UTC, taikiy commented
@benjaminsavage Thanks for reviewing! Fixed the code accordingly.

2022-05-12 02:18 UTC, benjaminsavage requested changes

2022-05-12 02:18 UTC, benjaminsavage commented on src/helpers/models.rs
> +type CipherText = BigInt;
@martinthomson - if we use some basic encryption approach like AES, what would be the right type signature to store those CipherTexts? Is it BigInt, or is it something else?

2022-05-12 02:18 UTC, benjaminsavage commented on src/helpers/models.rs
> +type PBRange = Range<u8>;
I don't think we want to use a Range for this. A range has a start and an end. The privacy budget a query will consume will be a fixed number, not something within a range.

2022-05-12 02:18 UTC, benjaminsavage commented on src/helpers/models.rs
> +    privacy_budget: PBRange,
How can we consume a range? We would consume a specific value.

2022-05-12 02:18 UTC, benjaminsavage commented on src/helpers/models.rs
> +    /// Date and time of the event occurence. Secret shared and encrypted.
It wouldn't be date and time. I would expect that the timestamp would just be an offset into a given Epoch. We probably need another field to indicate which Epoch we are in. That wouldn't need to be encrypted or secret shared - it could be in the clear. I'm not sure what's the best type to express the Epoch. @martinthomson - what do you think?

2022-05-12 02:18 UTC, benjaminsavage commented on src/helpers/models.rs
> +    /// The maximum number of attributed conversion events that a single person can contribute
I'm wondering if we should express the number of attributed conversion events, or if we should cap their sum of trigger value? I think they are equivalent since we will have range proofs that all the trigger values lie within a given range. I think this is fine for now until we have reason to change it.

2022-05-12 02:18 UTC, benjaminsavage commented on src/helpers/models.rs
> +    /// The range which all trigger event's conversion values must lie within.
nit: the trailing preposition bothers me =).

I suggest: "The range within which all the trigger event values must lie"

2022-05-12 05:00 UTC, martinthomson commented on src/helpers/models.rs
> +type CipherText = BigInt;
As a buffer of bytes generally, so `Vec<u8>` or `&[u8]` depending on whether you need a reference.

2022-05-12 05:06 UTC, martinthomson commented on src/helpers/models.rs
> +    /// Date and time of the event occurence. Secret shared and encrypted.
Within an epoch, we have 2^20 seconds, so u32 for that part would do.

For the epoch number, we only need to ensure that there are enough values that we can be reasonably sure that events won't be mistaken.  For instance, if you chose a 2 bit epoch, then every 4 epochs you would use the same number.  You would have to force helpers to rotate their keys more often than the rollover occurs.  Given that, an 8-bit value might be enough for the epoch as it is probably OK to force key rotations every 4 years.

Make it 16 bits and you never have to rotate keys, or at least you aren't forced to plan for key rotation.  That might not be good in that building and testing a critical function can be deferred indefinitely, after which dealing with a compromise becomes even worse.

2022-05-25 03:18 UTC, taikiy commented
@benjaminsavage I was offline for a several days last week. Updated the PR again. Thanks in advance!

2022-05-26 05:10 UTC, benjaminsavage approved these changes
Love it. Thank you for this!

2022-05-26 05:10 UTC, benjaminsavage commented on src/helpers/models.rs
> +    /// An offset in seconds into a given offset. The clear is u32 (< 2^20 seconds), then encrypted and secret shared.
"...into a given epoch."

2022-05-26 05:21 UTC, merged