Secure multiplication prototype using async/await model
martinthomson/raw-ipa pull request #55
Opened 2022-07-26 22:15 UTC by akoshelev

## Overview

This PR builds on top of https://github.com/martinthomson/raw-ipa/pull/49 and adds secure multiplication protocol using replicated secret sharing ([paper](https://eprint.iacr.org/2018/387.pdf)). 

The whole protocol is implemented inside `SecureMul` struct.

I wanted to make sure once we start using streams we would be able to adopt this approach, so this change also contains a stream implementation for secure multiplication where shares are fed to each helper using stream API. This looks mostly OK to me except that we need to pin stream to the heap because of `async` closure. 

Helper communication API deliberately kept small to make sure I don't accidentally add some features that would be hard to implement for real network communication. This change also brings `TestHelper` implementation that is used in unit tests.

2022-07-27 04:47 UTC, benjaminsavage requested changes
Just a few small changes requested.

2022-07-27 04:47 UTC, benjaminsavage commented on src/helpers/ring.rs
> +pub trait Ring {
I'll have to stop using the term "Ring" to refer to the concept in Mathematics: https://en.wikipedia.org/wiki/Ring_(mathematics)

That's fine - I think we don't need to draw any distinction with a field.

2022-07-27 04:47 UTC, benjaminsavage commented on src/helpers/ring.rs
> +/// too
Makes sense. I can imagine other cases where we could have a KING or some such thing (e.g. when all the helpers need to send data to a single place to be revealed).

2022-07-27 04:47 UTC, benjaminsavage commented on src/helpers/ring.rs
> +    async fn receive<T: Message>(&self, source: HelperAddr) -> Result<T, Error>;
Nice and simple!

2022-07-27 04:47 UTC, benjaminsavage commented on src/helpers/ring.rs
> +    #[derive(Debug)]
Thank you for this comment. Super helpful and very clear.

2022-07-27 04:47 UTC, benjaminsavage commented on src/helpers/ring.rs
> +            let (tx, mut rx) = channel::<MessageEnvelope>(buf_capacity);
What do "tx" and "rx" mean? These variable names aren't super obvious in their meaning (to me)

2022-07-27 04:47 UTC, benjaminsavage commented on src/helpers/ring.rs
> +            });
This is all greek to me.

2022-07-27 04:47 UTC, benjaminsavage commented on src/helpers/ring.rs
> +                HelperAddr::Right => (self.right.as_ref().unwrap(), HelperAddr::Left),
WTF? Left => Right and Right => Left?

2022-07-27 04:47 UTC, benjaminsavage commented on src/lib.rs
> +mod replicated_secret_sharing;
I can't help noticing this is the only one without a "pub" - why is that?

2022-07-27 04:47 UTC, benjaminsavage commented on src/replicated_secret_sharing.rs
> +        write!(f, ")")
Isn't there a way to put this on one line?

2022-07-27 04:47 UTC, benjaminsavage commented on src/securemul.rs
> +/// * [paper](https://eprint.iacr.org/2018/387.pdf)
/// IKHC multiplication protocol
/// for use with replicated secret sharing over some field `F`.
/// K. Chida, K. Hamada, D. Ikarashi, R. Kikuchi, and B. Pinkas. High-throughput secure AES computation. In WAHC@CCS 2018, pp. 13–24, 2018

2022-07-27 04:47 UTC, benjaminsavage commented on src/securemul.rs
> +    d: u128,
Woah... I don't think we need anything that big. Honestly - even a u32 is probably going to be enough for our usecase.

2022-07-27 04:47 UTC, benjaminsavage commented on src/securemul.rs
> +    d: u128,
It should be determined by `F`

2022-07-27 04:47 UTC, benjaminsavage commented on src/securemul.rs
> +            let rhs = a1 * b1 + s1 + F::from(right_d);
Just a nit - but can you put the terms in the same order?

That is, make the second line:

  let rhs = a1 * b1 + F::from(right_d) + s1;

2022-07-27 04:47 UTC, benjaminsavage commented on src/securemul.rs
> +    pub async fn execute<R: Ring>(
I see that we lost the Optimization here. that's fine - it keeps this diff simpler. We can add it later.

2022-07-27 04:47 UTC, benjaminsavage commented on src/securemul.rs
> +        fn poll_next(mut self: Pin<&mut Self>, cx: &mut Context<'_>) -> Poll<Option<Self::Item>> {
I'm surprised to see this living inside of securemul.rs - it seems generic and not scoped to just secure multiplication.

2022-07-27 04:47 UTC, benjaminsavage commented on src/securemul.rs
> +    {
I don't really understand what is going on here, and how (if at all), I as a protocol author need to interact with Streams.

2022-07-27 04:47 UTC, benjaminsavage commented on src/securemul.rs
> +                    stream.next().await.expect("Failed to compute a*b*c")
Is the intention for protocol authors to write code like this? I don't find this very transparent. It's not clear that this computes a*b*c - could we make that shine through more?

2022-07-27 04:47 UTC, benjaminsavage commented on src/securemul.rs
> +        let index = u128::from(INDEX.with(|i| i.fetch_add(1, Ordering::Release)));
What on earth is going on here?

2022-07-27 18:57 UTC, benjaminsavage commented on src/securemul.rs
> +    d: u128,
Fair enough.

2022-07-27 19:00 UTC, benjaminsavage commented on src/securemul.rs
> +                    stream.next().await.expect("Failed to compute a*b*c")
OK, I believe you.

2022-07-27 19:01 UTC, benjaminsavage commented on src/securemul.rs
> +        let index = u128::from(INDEX.with(|i| i.fetch_add(1, Ordering::Release)));
...is it worth it?

2022-07-27 19:02 UTC, benjaminsavage approved these changes
It may not be perfect - but this is blocking other development.

I think if we get this out we start using the await? syntax immediately - leading to better protocol development. 

In the meantime - we can continue to iterate on all the internals without needing to significantly alter the syntax. This seems like a good compromise to me.

2022-07-28 04:12 UTC, akoshelev commented
merging it as @martinthomson is away, will address the feedback afterwards if any.

2022-07-28 04:12 UTC, merged