vector
martinthomson/raw-ipa pull request #57
Opened 2022-07-28 23:12 UTC by algebravic

- add mp-spdz prototype, data generator, and readme
- add IPA_VERBOSE and IPA_NUMROWS_POWER as env variables to set at compile time
- remove using Public Input for row number, did not work
- use exec to unroll loops
- update readme to reflect updates to MP-SPDZ
- iron out final bugs
- add gitattributes for syntax highlighting for .mpc files
- rename _list to reports
- rename ambiguous variables, add Enum for Matrix columns
- Rewriting Erik's ipae2e.mpc using vectors instead of
- Rewrote Erik's code using vectors

2022-07-29 16:49 UTC, bmcase commented
Since this isn't doing a sort, it is really the create helperbits and oblivious attribution stages.   

The great news is the vector operations do seem to be really helping with the compile memory usage.  Comparing to just the oblivious attribution stage before this is using around 13x less memory.

2022-07-30 15:24 UTC, eriktaubeneck requested changes
Generally, there is A LOT going on here. It would be great if this was based off the existing `mp-spdz-prototype` branch, and edits were made directly to the ipae2e file, so that it was easy to see the differences. additionally, it would be great to have 1 PR for each incremental change, (i.e. one just focused on vectorization, and a different one with extra sort options, etc.)

2022-07-30 15:24 UTC, eriktaubeneck commented on research-prototype/Programs/Source/erik.mpc
> +        match_keys.assign_vector(sint.get_input_from(0, size = numrows))
these seem to consume different numbers of inputs

2022-07-30 15:24 UTC, eriktaubeneck commented on research-prototype/Programs/Source/erik.mpc
> +    if args.do_sort:
is there any reason we wouldn't do the sort?

2022-07-30 15:24 UTC, eriktaubeneck commented on research-prototype/Programs/Source/erik.mpc
> +def main():
not sure if this is particularly helpful? it just forces everything to be indented and doesn't actually change the functionality

2022-07-30 15:24 UTC, eriktaubeneck commented on research-prototype/Programs/Source/erik.mpc
> +BATCHER_SORT = 2
this would be much better as strings

2022-07-30 15:24 UTC, eriktaubeneck commented on research-prototype/Programs/Source/erik.mpc
> +BREAKDOWN_KEY = 2
why not continue to use the Enum.IntEnum?

2022-07-31 20:03 UTC, eriktaubeneck commented on research-prototype/Programs/Source/erik.mpc
> +    # of the file to be compiled.
found another bug this this... calling `../../MP-SPDZ/compile.py -C -R 32 ipae2e 10` ends up naming the compiled programs `ipae2e-10`, which means you have to specify which version you're running...

2022-08-01 06:33 UTC, closed without merging